import seedModelUsd from "../assets/predict_release_model_usd_seed.json";

export type PredictReleaseEvalThreshold = {
  th: number;
  acc: number;
  n: number;
  coverage: number;
};

export type PredictReleaseSubModel = {
  task?: string;
  requires_forecast?: boolean;
  features: string[];
  // Shape: [featureCount][3] for classes ["="," >", "<"] in this exact order.
  weights: number[][];
  recommended_threshold: number;
  eval?: {
    acc?: number;
    n?: number;
    confidence?: string;
    thresholds?: PredictReleaseEvalThreshold[];
  };
};

export type PredictReleaseModelFile = {
  schema: number;
  generated_at_utc?: string;
  meta?: {
    currency?: string;
    importance?: string[];
    eq_factor?: number;
    min_metric_points?: number;
  };
  classes: ["=", ">", "<"] | string[];
  models: {
    ap_with_forecast: PredictReleaseSubModel;
    ap_no_forecast: PredictReleaseSubModel;
    // Optional: expectation/surprise view when Forecast exists.
    af_with_forecast?: PredictReleaseSubModel;
  };
};

// Bundled fallback: generated by `scripts/calendar/train_predict_release_model.py`.
// Keep this local so ui-check/webview can still render Predict Release without a desktop backend.
export const DEFAULT_PREDICT_RELEASE_MODEL_USD: PredictReleaseModelFile =
  seedModelUsd as unknown as PredictReleaseModelFile;

export function softmax1d(scores: number[]): number[] {
  if (!scores.length) return [];
  const m = Math.max(...scores);
  const exps = scores.map((s) => Math.exp(s - m));
  const denom = exps.reduce((a, b) => a + b, 0);
  if (!Number.isFinite(denom) || denom <= 0) return scores.map(() => 1 / scores.length);
  return exps.map((v) => v / denom);
}

export function dotFeatures(weights: number[][], features: number[]): number[] {
  // weights: [d][k], features: [d] -> scores: [k]
  const d = Math.min(weights.length, features.length);
  const k = weights[0]?.length ?? 0;
  const out = new Array<number>(k).fill(0);
  for (let j = 0; j < d; j += 1) {
    const x = features[j] ?? 0;
    const row = weights[j] ?? [];
    for (let c = 0; c < k; c += 1) {
      out[c] = (out[c] ?? 0) + x * (row[c] ?? 0);
    }
  }
  return out;
}

export function estimateBacktestAccAtThreshold(sub: PredictReleaseSubModel): number | null {
  const th = sub.recommended_threshold;
  const rows = sub.eval?.thresholds ?? [];
  const hit = rows.find((r) => Math.abs(r.th - th) <= 1e-9);
  if (hit && typeof hit.acc === "number" && Number.isFinite(hit.acc)) return hit.acc;
  return null;
}
